### ISSUE TITLE
KeyError: 'rgb_level0'

### ISSUE THREAD

**Issue by wjlyu** [zju3dv/ENeRF#8]
I retrain with zjumocap dataset with command: python train_net.py --cfg_file configs/enerf/zjumocap_eval.yaml
while I get the error:
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Loading model from: /opt/conda/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth
Traceback (most recent call last):
  File "train_net.py", line 117, in <module>
    main()
  File "train_net.py", line 109, in main
    train(cfg, network)
  File "train_net.py", line 51, in train
    trainer.train(epoch, train_loader, optimizer, recorder)
  File "/dfs/data/ENeRF/lib/train/trainers/trainer.py", line 56, in train
    output, loss, loss_stats, image_stats = self.network(batch)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1015, in _call_impl
    return forward_call(*input, **kwargs)
  File "lib/train/losses/enerf.py", line 23, in forward
    color_loss = self.color_crit(batch[f'rgb_{i}'], output[f'rgb_level{i}'])
KeyError: 'rgb_level0'

**Comment by wjlyu** [comment]
I have fix the problem, because of level0 is not rendered.
thanks for your great work!
